let dataset = ['This is nice work :)',
'Please stop!',
'Delightful =) Adore the use of gradient and background!',
'Incredibly thought out! Wow love it!',
'Such sleek.',
'It\'s fun not just splendid!',
'Just fresh.',
'My 49 year old dad rates this style very delightful dude',
'I think I\'m crying. It\'s that revolutionary.',
'Trying it now.',
'Gorgeous. So minimal.',
'Excellent atmosphere m8',
'Lines, navigation, colour palette, boldness – appealing.',
'Nice use of sky blue in this camera angle!',
'Tremendously clean, friend.',
'Mission accomplished. It\'s classic dude',
'I want to learn this kind of background image! Teach me.',
'Simple work you have here.',
'It makes me laugh...',
'Love your shot mate',
'Let me take a nap... great concept, anyway.',
'Very fab shot :)',
'Such shot, many avatar, so clean',
'This shot blew my mind.',
'This shot has navigated right into my heart.',
'Cyan. You are so inspiring!',
'That\'s delightful and appealing, friend.',
'I like your shapes :-)']

module.exports = dataset;
